valtimo-platform/valtimo-documentation

release-notes/major9/09.17.0/valtimo-frontend-libraries.md
=> feat: add fe release notes

release-notes/major9/09.18.0/valtimo-frontend-libraries.md
=> feat: add user name top bar release note

release-notes/major9/09.18.0/valtimo-frontend-libraries.md
=> feat: add release notes for ng-bootstrap downgrade

release-notes/major9/09.18.0/valtimo-frontend-libraries.md
https://ritense.tpondemand.com/entity/35309-fe-wijzigen-bestaande-plugin-configuratie-plugin
=> feat: modify and/or delete plugin config release notes

release-notes/major9/09.18.0/valtimo-frontend-libraries.md
For https://ritense.tpondemand.com/entity/36285-be-fe-support-multiple-zgw-api (FE task)
=> feat: add multiple zgw fe release notes

release-notes/major9/09.18.0/valtimo-frontend-libraries.md
added documentation about new known issue cases sort by default at the same property key
=> feat: added documentation about new known issue cases sort by default

release-notes/major9/09.18.0/valtimo-frontend-libraries.md
=> feat: add release notes for tooltip

release-notes/major9/09.19.0/valtimo-frontend-libraries.md
=> feat: add front-end release notes

release-notes/major9/09.19.0/valtimo-frontend-libraries.md
* added documentation about new design dropdown
US: https://ritense.tpondemand.com/entity/36692-fe-new-design-dropdown-seems-disabled
=> feat: new design dropdown

release-notes/major9/09.19.0/valtimo-frontend-libraries.md
* add scroll to top at valtimo-modal
US: https://ritense.tpondemand.com/entity/35991-fe-modal-in-user-tasks-should
=> feat: scroll to top docu

release-notes/major9/09.19.0/valtimo-frontend-libraries.md
US: https://ritense.tpondemand.com/entity/36474-autofit-width-for-document-definition-name
=> feat: autofit width for document definition name

SUMMARY.md, extending-valtimo/extending-valtimo.md, extending-valtimo/tabs/customizing-case-tabs.md, extending-valtimo/tabs/tabs.md, release-notes/major9/09.19.0/valtimo-frontend-libraries.md
=> feat: add release notes zaakobjecten tab

release-notes/major9/09.19.0/valtimo-frontend-libraries.md
=> feat: add session timeout prompt release notes

release-notes/major9/09.19.0/valtimo-frontend-libraries.md
* add new input design documentation
*
US: https://ritense.tpondemand.com/entity/36873-fe-various-new-design-components-should
=> feat: add new input design documentation

release-notes/major9/09.19.0/valtimo-frontend-libraries.md
Reverts valtimo-platform/valtimo-documentation#60
=> Revert "feat: add new input design documentation"

release-notes/major9/09.19.0/valtimo-frontend-libraries.md
* add new input design documentation
US: https://ritense.tpondemand.com/entity/36873-fe-various-new-design-components-should
=> feat: new design components doc

release-notes/major9/09.19.0/valtimo-frontend-libraries.md
=> feat: add missing skeleton loader release note

reference/feature-toggles/available-feature-toggles.md, release-notes/major9/09.20.0/valtimo-frontend-libraries.md
=> feat: add release notes experimental dmn editing

release-notes/major9/09.20.0/valtimo-frontend-libraries.md
Add bugfix documentation for the fixes that have been made to the case detail component
=> Add bugfix documentation for the fixes

release-notes/major9/09.16.0/valtimo-frontend-libraries.md
Based on feedback received from managed services,
=> feat: improve form.ui dependency upgrade release note

release-notes/major9/09.18.0/valtimo-backend-libraries.md
Removing some release notes for a feature that did not get released in 9.18.0
=> remove misplaced changelog notes

release-notes/major9/09.21.0/valtimo-backend-libraries.md, release-notes/major9/09.21.0/valtimo-frontend-libraries.md
Added documentation for the following feature:
https://github.com/valtimo-platform/valtimo-frontend-libraries/pull/192
https://github.com/valtimo-platform/valtimo-backend-libraries/pull/287
=> added documentation for sorting processes on isActive

SUMMARY.md, release-notes/major9/09.21.0/valtimo-frontend-libraries.md, using-valtimo/upload/upload-to-documenten-api-with-metadata.md, using-valtimo/upload/upload.md, using-valtimo/using-valtimo.md
=> feat: add release notes; documenten api documentation

release-notes/major9/09.21.0/valtimo-frontend-libraries.md, using-valtimo/plugin/documenten-api/configure-documenten-api-plugin.md, using-valtimo/plugin/zaken-api/configure-zaken-api-plugin.md
Closes https://ritense.tpondemand.com/entity/37428-fe-create-components-for-new-plugin
=> feat: add new fe documentation for plugin actions

release-notes/major9/09.21.0/valtimo-frontend-libraries.md
=> feat: add release notes

reference/troubleshoot.md
Closes https://ritense.tpondemand.com/entity/37208-valtimo-upload-component-experiences-timeouts
=> feat: add formio known issue

release-notes/major9/09.16.0/valtimo-backend-libraries.md, release-notes/major9/09.17.0/valtimo-backend-libraries.md, release-notes/major9/09.18.0/valtimo-backend-libraries.md, release-notes/major9/09.19.0/valtimo-backend-libraries.md, release-notes/major9/09.20.0/valtimo-backend-libraries.md, release-notes/major9/09.21.0/valtimo-backend-libraries.md
* added a feature description to the next release notes about [PR 327](https://github.com/valtimo-platform/valtimo-backend-libraries/pull/327)
=> feat: documentation for valtimo-backend-libraries PR 327

release-notes/major9/09.22.0/valtimo-frontend-libraries.md
Small part on the translations that have been added.
=> Add translations to a few components

release-notes/major10/10.0.0/migration.md, release-notes/major10/10.0.0/valtimo-frontend-libraries.md
For Angular and Node.js upgrades.
=> feat: add fe major 10 release notes

release-notes/major9/09.23.0/valtimo-frontend-libraries.md
* added documentation about new default column assignee
US: https://ritense.tpondemand.com/entity/37406-fe-show-case-assignee-in-case
=> doc:  new default column assignee

release-notes/major9/09.23.0/valtimo-frontend-libraries.md
=> feat: add flatpickr bugfix rn

README.md, SUMMARY.md, extending-valtimo/extending-valtimo.md, reference/reference.md, release-notes/release-notes.md, using-valtimo/using-valtimo.md, valtimo-implementation/valtimo-implementation.md
Added a paragraph to each main section about what that section contains and what the target audience is.
=> Added description for each main section

release-notes/major9/09.23.0/valtimo-frontend-libraries.md
closes: https://ritense.tpondemand.com/entity/37413-fe-claim-case-on-case-detail
=> doc: Added 'Claim' button on case detail page

release-notes/major9/09.24.0/valtimo-frontend-libraries.md
closes: https://ritense.tpondemand.com/entity/37410-fe-assign-assignee-to-case
=> doc: assign assignee link

release-notes/major10/10.0.0/migration.md, release-notes/major10/10.0.0/valtimo-backend-libraries.md
Depends on [this PR](https://github.com/valtimo-platform/valtimo-migration/pull/2) before it can be merged.
=> added release notes for removing process data objects

release-notes/major10/10.0.0/valtimo-frontend-libraries.md
Closes: https://ritense.tpondemand.com/entity/37400-fe-change-fe-version-to-be
=> doc: changed versions

release-notes/major10/10.0.0/migration.md, release-notes/major10/10.0.0/valtimo-frontend-libraries.md
=> feat: add front-end dependency upgrades release notes

release-notes/major9/09.25.0/valtimo-frontend-libraries.md
=> feat: add persist query params release notes

release-notes/major10/10.0.0/migration.md, release-notes/major10/10.0.0/valtimo-frontend-libraries.md
For: https://ritense.tpondemand.com/entity/31954-befe-remove-auth0-from-libraries.
=> feat: add remove auth0 release notes and migration

extending-valtimo/forms/creating-form-field-data-resolver.md, release-notes/major9/09.16.0/valtimo-backend-libraries.md, release-notes/major9/09.17.0/valtimo-backend-libraries.md, release-notes/major9/09.18.0/valtimo-backend-libraries.md, using-valtimo/document/assigning-a-user.md
For S=C I reviewed the documentation and made some minor changes. Looks good!
=> general doc review wouter de wijn

release-notes/major9/09.26.0/valtimo-frontend-libraries.md
Added bugfix "Size of collection in Dossier list"
=> Description of the size of collection bugfix in valtimo-frontend-libraries.md

release-notes/major9/09.26.0/valtimo-frontend-libraries.md
Closes US: https://ritense.tpondemand.com/entity/43545-fe-tab-list-columns-on-case
=> feat: doc add new tab list

SUMMARY.md, reference/user-interface/carbon-design-system.md, reference/user-interface/design-philosophy.md, reference/user-interface/user-interface.md, release-notes/major10/10.0.0/migration.md, release-notes/major10/10.0.0/valtimo-frontend-libraries.md
For: https://ritense.tpondemand.com/entity/37982-fe-add-carbon-shell-to-valtimo
=> feat: add carbon release notes

reference/feature-toggles.md
ClosesUS: https://ritense.tpondemand.com/entity/43545-fe-tab-list-columns-on-case
=> doc: case list column featureToggle

release-notes/major9/09.26.0/valtimo-frontend-libraries.md
For: https://ritense.tpondemand.com/entity/37538-fe-only-show-case-assignee-if
=> feat: add 'can have assignee' functionality release notes

valtimo-implementation/compatibility-matrix.md
=> feat: compatibility matrix feedback

valtimo-implementation/modules/modules.md, valtimo-implementation/modules/zgw/notificaties-api.md
* adds new Notificaties API page and entry to modules.md
=> feat: 46692 notificaties api module

release-notes/major10/10.2.0/valtimo-backend-libraries.md, release-notes/major10/10.2.0/valtimo-frontend-libraries.md
* adds initial documentation for the new Notificaties API plugin
=> feat: 46732 notifiacties api plugin

release-notes/major10/10.2.0/valtimo-frontend-libraries.md
Current user Form-io custom component
=> Added new feature

release-notes/major10/10.2.0/valtimo-frontend-libraries.md
=> Updated release notes

release-notes/major10/10.2.0/valtimo-frontend-libraries.md
Documentation for https://github.com/valtimo-platform/valtimo-frontend-libraries/pull/316
=> Feature/move audit time to date 10.2.0

release-notes/major10/10.2.0/valtimo-backend-libraries.md
* adds initial documentation for the new OpenNotificaties plugin
=> feat: 46996 open notifiacties auth plugin

release-notes/major10/10.2.0/valtimo-frontend-libraries.md
=> feat: add documentation editing case list columns

release-notes/major10/10.2.0/valtimo-frontend-libraries.md
See [story](https://ritense.tpondemand.com/restui/board.aspx?#page=userstory/45195).
- TP-45195 - Added documentation for the audit trail dots.
=> TP-45195 - Added documentation for the audit trail dots.

release-notes/major10/10.3.0/valtimo-frontend-libraries.md
https://ritense.tpondemand.com/entity/35799-febe-duplicate-existing-formio-definition-to
=> tp-35799 add duplicate form docs

extending-valtimo/plugin/custom-plugin-definition.md, introduction/modules/modules.md, introduction/modules/plugin-introduction.md, release-notes/major10/10.3.0/valtimo-backend-libraries.md
* documentation for notificaties api and plugin events
=> feat: 47126 notificaties api and plugin events documentation

reference/feature-toggles.md, release-notes/major10/10.4.0/valtimo-frontend-libraries.md
For https://ritense.tpondemand.com/entity/51591-fe-sort-related-files-by-date
=> feat: add documentation sort file feature toggle

extending-valtimo/plugin/custom-plugin-definition.md, getting-started/modules/zgw/openzaak.md
Current documentation is missing some important steps
=> -added documentation for necessary steps to implement a custom plugin

SUMMARY.md, release-notes/major10/10.5.0/migration.md, release-notes/major10/10.5.0/valtimo-backend-libraries.md, release-notes/major10/10.5.0/valtimo-frontend-libraries.md
documents https://github.com/valtimo-platform/valtimo-backend-libraries/pull/604
=> bugfix for duplicate results when retrieving process instance variables

release-notes/major10/10.6.0/valtimo-backend-libraries.md
Note: This goes to the release notes of **10.6.0**
=> #36301 release notes plugin action to create a 'Zaakresultaat'

reference/feature-toggles.md, release-notes/major10/10.6.0/valtimo-frontend-libraries.md
=> Feature/release notes 10.6.0 application title as suffix featuretoggle

release-notes/major10/10.7.0/valtimo-backend-libraries.md
a new feature entry is added for the following PR: https://github.com/valtimo-platform/valtimo-backend-libraries/pull/755
=> feat: pr 755 documentation

release-notes/major10/10.7.0/valtimo-backend-libraries.md
=> Added known issue to release notes:

getting-started/modules/zgw/besluiten-api.md, getting-started/modules/zgw/catalogi-api.md, getting-started/modules/zgw/documenten-api.md, getting-started/modules/zgw/notificaties-api.md, getting-started/modules/zgw/objecten-api-authentication.md, getting-started/modules/zgw/objecten-api.md, getting-started/modules/zgw/objecttypen-api.md, getting-started/modules/zgw/zaken-api.md
The frontend also needs to be updated before the plugin becomes selectable.
I've updated the documentation on all the <plugin> API pages to include the required frontend adjustments
=> feature - Setting up plugins is more than just adding backend dependencies

reference/user-interface/breadcrumbs.md, release-notes/major10/10.7.0/valtimo-frontend-libraries.md
=> feat: extend breadcrumbs docu, add open in new tab release notes

SUMMARY.md, release-notes/major11/11.0.0/valtimo-frontend-libraries.md, using-valtimo/access-control/access-control.md, using-valtimo/access-control/frontend-access-control.md, using-valtimo/using-valtimo.md
=> feat: add front-end access control docu

SUMMARY.md, getting-started/modules/core/authorization.md, getting-started/modules/modules.md, introduction/modules/modules.md, release-notes/major11/11.0.0/valtimo-backend-libraries.md, using-valtimo/access-control/access-control.md, using-valtimo/access-control/backend-access-control.md, using-valtimo/access-control/frontend-access-control.md
- Explanation what the module is and is meant to be used for.
- How to include it in your project
- How to configure roles and permissions in BE
=> 66304 - PBAC feature

release-notes/major10/10.7.0/valtimo-frontend-libraries.md
=> feat: add known issue ng-multiselect

release-notes/major11/11.0.0/valtimo-backend-libraries.md
Added documentation for choice field values bugfix
=> Added documentation for choice field values bugfix

release-notes/major11/11.1.0/valtimo-backend-libraries.md
For https://ritense.tpondemand.com/entity/71945-be-cant-upload-dmn
=> feat: dmn upload fix release note

reference/feature-toggles.md, using-valtimo/case/case-tabs.md
=> feat: feature toggle docu

reference/modules/authorization.md, release-notes/major11/11.0.0/valtimo-backend-libraries.md
Several additions to:
- reference/authorization.md
- 11.0.0/valtimo-backend-libraries.md
=> Several additions

reference/modules/cloud-events.md, release-notes/major11/11.2.0/valtimo-backend-libraries.md
for https://ritense.tpondemand.com/entity/87517-be-emit-events-for-actions-on and https://ritense.tpondemand.com/entity/87514-be-emit-events-for-actions-on
=> feat: new events documentation

release-notes/major11/11.0.0/valtimo-frontend-libraries.md
=> feat: missing docu main

release-notes/major11/11.2.0/valtimo-frontend-libraries.md
=> feat: missing release notes 11.2

release-notes/major11/11.0.0/valtimo-frontend-libraries.md, release-notes/major11/11.1.0/valtimo-frontend-libraries.md
=> fix: broken carbon overlay components docu

release-notes/major11/11.1.0/valtimo-frontend-libraries.md, release-notes/major11/11.2.0/valtimo-frontend-libraries.md
=> feat: missing docu 11.2.0

release-notes/major11/11.2.0/valtimo-frontend-libraries.md
Documentation for:
- [[FE] Retrieve and update process-document-definitions for a specific version](https://ritense.tpondemand.com/entity/92554-fe-retrieve-and-update-process-document)
- [[FE] Implement Carbon list on case definition list page](https://ritense.tpondemand.com/entity/92558-fe-implement-carbon-list-on-case)
- [[FE] Make it Carbon: tab search fields](https://ritense.tpondemand.com/entity/95112-fe-make-it-carbon-tab-search)
- [[FE] Tab for 'Processes'](https://ritense.tpondemand.com/entity/95116-fe-tab-for-processes)
- [[FE] Implement Carbon list on plugin list page](https://ritense.tpondemand.com/entity/92560-fe-implement-carbon-list-on-plugin)
=> Added documentation for carbonization of components and processes tab

release-notes/major11/11.0.0/migration.md
=> feat: update migration notes

release-notes/major11/11.2.0/valtimo-frontend-libraries.md
[[FE] fix broken z-indexes carbon components](https://ritense.tpondemand.com/entity/93753-fe-fix-broken-z-indexes-carbon)
=> Add documentation for z-index fix

SUMMARY.md, release-notes/major11/11.1.1/valtimo-backend-libraries.md, release-notes/major11/11.1.1/valtimo-frontend-libraries.md
[[FE] Empty dropdown Widget datasource](https://ritense.tpondemand.com/entity/96875-fe-empty-dropdown-widget-datasource)
=> Add documentation for widget datasource fix

using-valtimo/form-flow/create-custom-component.md
=> feat: improve custom form flow component documentation

release-notes/major11/11.1.2/valtimo-frontend-libraries.md
for https://ritense.tpondemand.com/entity/104310-fe-fix-custom-form-flow-components
=> feat: custom form flow components release notes

release-notes/major11/11.1.2/valtimo-frontend-libraries.md
[[FE] Pending changes guard does not work with breadcrumbs](https://ritense.tpondemand.com/entity/99757-fe-pending-changes-guard-does-not)
=> Add documentation for pending changes fix

release-notes/major11/11.1.2/valtimo-frontend-libraries.md
=> fix: formio notes

release-notes/major11/11.1.2/valtimo-frontend-libraries.md, release-notes/major12/12.0.0/migration.md, release-notes/major12/12.0.0/valtimo-frontend-libraries.md
=> feat: add missing docu 12.0

reference/feature-toggles.md, reference/user-interface/carbon-design-system.md, reference/user-interface/theme.md, reference/user-interface/user-interface.md, release-notes/major12/12.0.0/migration.md, release-notes/major12/12.0.0/valtimo-frontend-libraries.md
Updated documentation to properly reflect the new theming together with dark-mode.
=> Added documentation for theming and dark-mode

release-notes/major12/12.0.0/valtimo-frontend-libraries.md
Added 6 new illustrations for empty-state
=> Empty-state artwork update

release-notes/major12/12.0.0/migration.md, release-notes/major12/12.0.0/valtimo-frontend-libraries.md
Is supposed to describe functionality of this story: 109309
=> feat: zgw lib documentation

SUMMARY.md, release-notes/major11/11.3.2/valtimo-frontend-libraries.md
=> feat: formio token release note

release-notes/major12/12.1.0/valtimo-frontend-libraries.md
Documentation for updated modals for adding and updating a plugin
=> Update documentation for plugin modal

SUMMARY.md, getting-started/compatibility-matrix.md, release-notes/major9/09.26.2/valtimo-frontend-libraries.md
=> Merge 11.0 to 11.1

SUMMARY.md, getting-started/compatibility-matrix.md, release-notes/major9/09.26.2/valtimo-frontend-libraries.md
=> Merge 11.1 into 11.2

SUMMARY.md, getting-started/compatibility-matrix.md, release-notes/major9/09.26.2/valtimo-frontend-libraries.md
=> Merge 11.2 into 11.3

release-notes/major12/12.1.0/valtimo-frontend-libraries.md
for https://ritense.tpondemand.com/entity/114919-fe-change-case-tab-to-carbon
=> feat: design change release note

reference/modules/authorization.md, release-notes/major12/12.1.0/valtimo-backend-libraries.md
* Removed templates. (#703)
* Added release notes on dashboard AC.
=> Feature/release notes dashboard ac (#704)

SUMMARY.md, release-notes/major12/12.1.2/valtimo-backend-libraries.md
119365 - Intermediate save doesn't work when useridentifier is set to username
=> 119365 - Intermediate save doesn't work with useridentifier

release-notes/major12/12.2.0/migration.md, release-notes/major12/12.2.0/valtimo-frontend-libraries.md
=> feat: missing release notes 12.2

release-notes/major12/12.3.0/valtimo-backend-libraries.md
Added release notes for the backend feature filter-zaakinformatieobjecttypen
=> Added feature release notes

release-notes/major12/12.4.0/migration.md, release-notes/major12/12.4.0/valtimo-backend-libraries.md, release-notes/major12/12.4.0/valtimo-frontend-libraries.md
for https://ritense.tpondemand.com/entity/117031-be-change-logging-user-anonymous-to
=> feat: add audit author release note

reference/feature-toggles.md
(cherry picked from commit 20f9d7c2a71625eef426eaf1fe166b0febc28775)
=> Added `enableIntermediateSave` to the feature toggles page

release-notes/12.x.x/12.1.0.md
=> story: old release note form view model

release-notes/12.x.x/12.6.0.md
=> story: port old fvm docu

release-notes/13.x.x/13.1.2/README.md
https://github.com/generiekzaakafhandelcomponent/gzac-issues/issues/227
=> Feature ctrl+click
